---
abstract: 'Avoid running under CPAN Testers'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-NoAutomatedTesting
requires:
  Dist::Zilla: 4.101582
  perl: 5.008005
resources:
  homepage: https://github.com/bingos/dist-zilla-plugin-noautomatedtesting
  repository: https://github.com/bingos/dist-zilla-plugin-noautomatedtesting.git
version: 0.04
