---
abstract: 'Avoid running under CPAN Testers'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-NoAutomatedTesting
requires:
  Dist::Zilla: 4.101582
  perl: 5.008005
resources:
  homepage: http://github.com/bingos/dist-zilla-plugin-noautomatedtesting/tree
  repository: git://github.com/bingos/dist-zilla-plugin-noautomatedtesting.git
version: 0.02
